### ISSUE TITLE
Why is there a Labwares() class and a Labware() class?

### ISSUE THREAD

**Issue by kosonocky** [JuBiotech/robotools#18]
robotools/liquidhandling/__init__.py has a Labware() class (~line 141) that contains the general object for defining labware.  This makes sense to me.

robotools/evotools/__init__.py has a Labwares() class (~line 17) that only contains:

`SystemLiquid = "Systemliquid"`

I don't understand why this is a separate class.  Could this be combined with the Labware() class?  Or should this stay separate? 
 If it should be separate, I think we should rename this class to something more distinct to avoid confusion.  The only reference to Labwares() that I see in this library is in tests.py (line 591):

`    def test_aspirate_systemliquid(self) -> None:
        with evotools.Worklist() as wl:
            wl.aspirate_well(evotools.Labwares.SystemLiquid, 1, 200)
            self.assertEqual(wl[-1], "A;Systemliquid;;;1;;200.00;;;;")
        return`

Is SystemLiquid just a specific default location on the Tecan?

Thanks,
Clay

**Comment by michaelosthege** [comment]
Yes, the (virtual) `Systemliquid` labware can be used to "aspirate" the system liquid of the liquid handler when using fixed tips.

Pipetting system liquid is less accurate because there are no air gaps, but it can be useful to pipet, for example a counterweight/tara well, because it's a little faster than aspirating from a trough.

I agree that the naming of the `Labwares` class is confusing.
