### ISSUE TITLE
Compatability with DiTi Evos

### ISSUE THREAD

**Issue by NikolasvdEichen** [JuBiotech/robotools#77]
Hey everyone,
I encountered an issue while using evos that mount disposable tips.
Unlike the Fluent, it does not understand a "W1;" as a "Eject Tips", but it has to be a ""W;". However, this is currently forbidden by the .wash method of the base worklist. What I'd suggest is the following
```python
    def wash(self, scheme: int = 1) -> None:
        """Washes fixed tips or replaces DiTis.

        Washes/replaces the tip that was used by the preceding aspirate record(s).

        Parameters
        ----------
        scheme : int
            Number indicating the wash scheme (default: 1)
        """
        if not scheme in {0, 1, 2, 3, 4}:
            raise ValueError("scheme must be either 0, 1, 2, 3 or 4")
        
        if scheme == 0:
            self.append("W;")
        else:
            self.append(f"W{scheme};")
        return
```

What do you guys think? I'd create a PR myself but I do not have write access.

**Comment by michaelosthege** [comment]
How is the interplay with `.transfer()` based commands? Would you do `.transfer(..., wash_scheme=0)`?

I guess then it's a good idea to allow `scheme=0`.

An alternative would be the introduction of a `(Evo)Worklist.eject_tips()` method. Might be more discoverable for users.

I'm open to either or both solutions.

@NikolasvdEichen you can [fork](https://github.com/JuBiotech/robotools/fork) and after pushing a branch to your own fork (`git add myfork https://github.com/.../robotools` ...) GitHub will show the "Create Merge Request" button.

**Comment by NikolasvdEichen** [comment]
The tip drop destination is specified in the load worklist dialogue. 
Yes, I would use the .transfer with wash_scheme = 0. Given that you need a "W;" for each individual pipetting operation, I think that would be the simplest way to implement it. 
I'll create a fork + merge request asap.

**Comment by michaelosthege** [comment]
Looking into this, I realized that we need to be careful:

### Fluent

`FluentWorklist.transfer(wash_scheme=None)` inserts a `flush()`→`F;` instead of a `W1;`.

### EVO

`EvoWorklist.transfer(wash_scheme=None)` violates the currently advertised method signature, but is handled as _not inserting a wash_.
→ The worklist runs (I thought this was invalid?!) but uses only Tip 1. My EVO Sim has fixed tips and washes them inbetween.

Using `W;` uses all tips at the same time, and with fixed tips it does a wash. According to you, this does not drop DiTis. However, I could not reproduce this in the EVO Sim.

Using a `F;` instead of a `W;` results in using only Tip 1 (with fixed and DiTis, in the EVO Sim).


------------

For the Fluent we implemented the "don't drop DiTis" via `wash_scheme=None` and inserting a `F;`, therefore I think we should also do `wash_scheme=None` not `wash_scheme=0` for the EVO.

But I'm not sure about inserting nothing (current implementation) vs. `W;` vs. `F;`.

What do you think, @NikolasvdEichen ?
